# Start from the n8n image
FROM n8nio/n8n:0.235.0-debian


RUN apt-get update
RUN apt-get install -y python3 python3-pip git sshpass
RUN openssl req -x509 -nodes -days 3650 -newkey rsa:4096 -keyout /opt/hostname.key -out /opt/hostname.crt -subj "/C=FR/ST=France/L=Paris/O=entreprise/CN=fqdn"
RUN chmod 777 -R /opt

ENV N8N_SSL_KEY=/opt/hostname.key
ENV N8N_SSL_CERT=/opt/hostname.crt
ENV N8N_PROTOCOL=https
ENV N8N_PORT=443

VOLUME n8n-app


ENTRYPOINT [ "n8n" ]
